fix: tighten up tests and pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,38 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+die () {
+    echo "*** ERROR ***"
+    echo >&2 "ERROR: $@"
+    exit 1
+}
+
 actionlint
+
+if [ "$?" -ne "0" ]; then
+  die "actionlint command failed. Check workflow syntax."
+fi
 
 npm run lint
 
-# NOTE: that pre-test runs build too
-npm test && npm run package
+if [ "$?" -ne "0" ]; then
+  die "lint script failed"
+fi
+
+npm run build
+if [ "$?" -ne "0" ]; then
+  die "build script failed"
+fi
+
+npm test
+if [ "$?" -ne "0" ]; then
+  die "test script failed"
+fi
+
+npm run package
+if [ "$?" -ne "0" ]; then
+  die "package script failed"
+fi
 
 if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
   echo "Detected uncommitted changes after build.  See status below:"
