fix: attempt approval with ineligible reviewer to get more info with permission issues (#23)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -35,7 +35,9 @@ if [ "$?" -ne "0" ]; then
 fi
 
 if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
-  echo "Detected uncommitted changes after build.  See status below:"
+  echo "\n*** ERROR ***"
+  echo "Detected uncommitted changes after build.  See status below:\n"
   git diff dist/
-  exit 1
+  echo ""
+  exit 2
 fi
